Implemented MMA solver using Primal-Dual subsolve

diff --git a/miniapps/mtop/makefile b/miniapps/mtop/makefile
--- a/miniapps/mtop/makefile
+++ b/miniapps/mtop/makefile
@@ -26,6 +26,7 @@ MFEM_LIB_FILE = mfem_is_not_built
 -include $(CONFIG_MK)
 
 MTOP_COMMON_SRC = mtop_integrators.cpp paramnonlinearform.cpp pparamnonlinearform.cpp
+MMA_SRC = MMA_Benchmark.cpp mtop_MMA.cpp mtop_MMA.hpp
 
 MTOP_COMMON_OBJ = $(MTOP_COMMON_SRC:.cpp=.o)
 
@@ -56,6 +57,21 @@ all: $(MINIAPPS)
 MFEM_TESTS = MINIAPPS
 include $(MFEM_TEST_MK)
 
+ASTYLE_BIN = astyle
+ASTYLE = $(ASTYLE_BIN) --options=$(SRC)config/mfem.astylerc
+ASTYLE_VER = "Artistic Style Version 3.1"
+FORMAT_FILES = $(foreach dir,$(DIRS) $(EM_DIRS) config,$(dir)/*.?pp)
+FORMAT_FILES += tests/unit/*.?pp
+UNIT_TESTS_SUBDIRS = general linalg mesh fem miniapps ceed
+MINIAPPS_SUBDIRS = dpg/util hooke/operators hooke/preconditioners hooke/materials hooke/kernels
+FORMAT_FILES += $(foreach dir,$(UNIT_TESTS_SUBDIRS),tests/unit/$(dir)/*.?pp)
+FORMAT_FILES += $(foreach dir,$(MINIAPPS_SUBDIRS),miniapps/$(dir)/*.?pp)
+FORMAT_EXCLUDE = general/tinyxml2.cpp tests/unit/catch.hpp
+FORMAT_LIST = $(filter-out $(FORMAT_EXCLUDE),$(wildcard $(FORMAT_FILES)))
+
+COUT_CERR_FILES = $(foreach dir,$(DIRS),$(dir)/*.[ch]pp)
+COUT_CERR_EXCLUDE = '^general/error\.cpp' '^general/globals\.[ch]pp'
+
 # Testing: Parallel vs. serial runs
 RUN_MPI = $(MFEM_MPIEXEC) $(MFEM_MPIEXEC_NP) $(MFEM_MPI_NP)
 TEST_NAME := MTop miniapp
@@ -78,3 +94,37 @@ clean-build:
 
 clean-exec:
 	@rm -rf SeqHeat* ParHeat*
+
+# $(call mfem_check_command, command-to-execute, success_msg, failed_msg)
+mfem_check_command = \
+  if [ -t 1 ]; then red="\033[0;31m"; green="\033[0;32m"; end="\033[0m"; fi;\
+  if ! $(1); then\
+    printf $$green"%s"$$end"\n" "[  OK  ] "$(strip $(2));\
+  else\
+    printf $$red"%s"$$end"\n"   "[FAILED] "$(strip $(3)); err_code=1;\
+  fi
+# Verify the C++ code styling in MFEM and check that std::cout and std::cerr are
+# not used in the library (use mfem::out and mfem::err instead).
+style:
+	@echo "Applying C++ code style..."
+	@astyle_version="$$($(ASTYLE_BIN) --version)";\
+	 if [ "$$astyle_version" != $(ASTYLE_VER) ]; then\
+	    printf "%s\n" "Invalid astyle version: '$$astyle_version'"\
+	           "Please use: '"$(ASTYLE_VER)"'";\
+	    exit 1;\
+	 fi
+	@err_code=0;\
+	$(call mfem_check_command,\
+	    $(ASTYLE) $(FORMAT_LIST) | grep Formatted,\
+	    "No source files were changed",\
+	    "Please make sure the changes are committed");\
+	echo "Checking for use of std::cout...";\
+	$(call mfem_check_command,\
+	   grep cout $(MMA_SRC) | grep -v $(COUT_CERR_EXCLUDE:%=-e %),\
+	   "No use of std::cout found", "Use mfem::out instead of std::cout");\
+	echo "Checking for use of std::cerr...";\
+	$(call mfem_check_command,\
+	   grep cerr $(MMA_SRC) |\
+	      grep -v $(COUT_CERR_EXCLUDE:%=-e %) -e cerrno,\
+	   "No use of std::cerr found", "Use mfem::err instead of std::cerr");\
+	exit $$err_code
